export enum ServiceManager {
    SERVICE_PRODUCTOS = 'productos',
    SERVICE_PROVINCIAS = 'provincias',
    SERVICE_CANTONES= 'cantones',
    SERVICE_TIPOS_IDENTIFICACION= 'tipos-identificacion',
    SERVICE_TERMINOS= "terminos",
    SERVICE_TIPOS_PERSONA= "tipos-persona",
    SERVICE_FUNCIONES= "funciones",
    SERVICE_PERSONAS= "personas",
    SERVICE_CATEGORIAS= "categorias",
    SERVICE_MARCAS= "marcas",  
    SERVICE_LOTES= 'lotes',
    SERVICE_DETALLE_LOTES= 'detalle-lotes',
    SERVICE_DETALLES_PRODUCTOS_LOTE= 'detalles-productos-lotes',
    SERVICE_PROVEEDORES= "proveedores",
    SERVICE_PARAMETROS= "parametros",
    SERVICE_PRECIOS_PRODUCTO= "precios-productos",
    SERVICE_DETALLES_PRODUCTO= "detalles-productos",
    SERVICE_IMAGENES_PRODUCTO= "imagenes-producto",
    SERVICE_PROFORMAS= "proformas",
    SERVICE_FACTURAS= "facturas",
    SERVICE_DETALLES_PROFORMAS= "detalles-proformas",
    AZURESASTOKEN= 'sp=racwdli&st=2022-03-17T18=40=05Z&se=2032-03-18T02=40=05Z&spr=https&sv=2020-08-04&sr=c&sig=W%2BVCKSAuPdyhMIwfn2hl0tQeP9hz2ToZd%2F%2BeJZqsufk%3D',
    AZUREACCOUNTNAME= 'distribuidorarf',
    AZURECONTAINERNAME= 'productos',
    SERVICE_GALERIA_PRODUCTO= "galeria-productos",
    SERVICE_KARDEX= "kardex",
    SERVICE_PROCEDIMIENTOS_DB= "procedimientos-db",
    SERVICE_VERSIONES_PROFORMAS= "versiones-proformas",
    MAX_INTENTOS= 3,
}
